# Generated by Django 4.2.5 on 2023-09-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='number')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, null=True, verbose_name='subtitle')),
                ('authors', models.TextField(null=True, verbose_name='authors')),
                ('publisher', models.CharField(max_length=255, null=True, verbose_name='publisher')),
                ('published_date', models.DateField(null=True, verbose_name='published date')),
                ('category', models.CharField(max_length=255, null=True, verbose_name='category')),
                ('distrubution_expense', models.FloatField(verbose_name='distribution expense')),
            ],
        ),
        migrations.CreateModel(
            name='BookSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.BooleanField(default=None)),
                ('Book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_search_for_get_report', to='rumiPanel.book')),
            ],
        ),
    ]
