# Generated by Django 4.2.5 on 2023-09-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=255, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtitle')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('publisher', models.CharField(max_length=255, verbose_name='publisher')),
                ('published_date', models.DateField(auto_now=True, verbose_name='published date')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('distrubution_expense', models.FloatField(verbose_name='distribution expense')),
            ],
        ),
    ]
