# Generated by Django 4.2.5 on 2023-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumiPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tick',
            field=models.BooleanField(default=None),
        ),
        migrations.DeleteModel(
            name='BookSearch',
        ),
    ]
